name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '17'
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: Build via Maven
      run: mvn verify -B --file pom.xml -DdisableXmlReport=true
    - name: Upload Files
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "Release Build"
        path: "*"
